name: "Install TPS"
description: ""
runs:
  using: "composite"
  steps:
    - name: Install dependencies and TPS
      shell: bash
      run: |
        sudo apt-get install dos2unix python3-setuptools
        sudo python3 -m pip install psutil

        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ioi-2017/tps/master/online-installer/install.sh)"
