name: "Get changes"
description: "Get changed files in commits"
outputs:
  changes:
    description: "Commit changes"
    value: ${{ steps.process-changes.outputs.changes }}
runs:
  using: "composite"
  steps:
    - name: Get problems
      id: all-problems
      uses: TNFSH-Programming-Contest/tps-actions/.github/actions/get-problems@main

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        list-files: 'json'
        filters: |
          input:
            - '*/gen/**'
          solutions:
            - '*/solution/**'
            - '*/solutions.json'
          pdf:
            - '*/scripts/statement.sh'
            - '*/statement/*.jpg'
            - '*/statement/DISABLE_AUTO_BUILD'
            - '*/statement/index.md'
          template:
            - 'template.tex'
          cover:
            - 'cover.tex'
          any:
            - 'p*/**'

    - name: Process
      id: process-changes
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        CHANGES: ${{ toJSON(steps.changes.outputs) }}
        PROBLEMS: ${{ steps.all-problems.outputs.problemsjson }}
      run: |
        python3 parse.py
